const KNOCKOUT_QUALITIES=new Set(['Spousal Cooperation','Effectively Builds Relationships','Visionizing Capacity','Relates to the Lost and Unchurched','Creates Ministry Ownership','Intrinsically Motivated']);
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function chartColor(score){if(score===null)return '#94a3b8'; const n=Number(score); if(n<3)return 'rgb(79,120,190)'; if(n===3)return 'rgb(100,116,139)'; return 'rgb(42,157,143)'}
function qualityNameHtml(name){return KNOCKOUT_QUALITIES.has(name)?`<strong class="knockoutQuality">${esc(name)}<span class="knockoutStar">*</span></strong>`:esc(name)}
function visualScoreChart(results){return `<section class="reportSection"><h3>Character Quality Score Profile</h3><p class="muted">The center line is the baseline score of 3.0. Each dot shows where that quality landed in relation to the baseline.</p><div class="profileLegend"><span>Lower</span><span>Baseline: 3.0</span><span>Higher</span></div><div class="profileChart">${results.map(r=>{const hasScore=!(r.score===null||r.score===undefined); const point=hasScore?((Number(r.score)-1)/4)*100:50; const width=hasScore?Math.abs(point-50):0; const left=hasScore?Math.min(point,50):50; const color=chartColor(r.score); return `<div class="profileRow"><div class="profileName">${qualityNameHtml(r.name)}</div><div class="profileTrack"><span class="baselineMarker"></span>${hasScore?`<span class="deviationBar" style="left:${left}%;width:${width}%;background:${color};"></span><span class="scoreDot" style="left:${point}%;background:${color};"></span>`:`<span class="naDot">N/A</span>`}</div><div class="profileValue"><strong>${esc(r.score??'N/A')}</strong><span>${esc(r.label)}</span></div></div>`}).join('')}</div></section>`}
function scoreColor(v){v=Number(v)||0; if(v>=85)return '#6c9f3f'; if(v>=70)return '#9bbf2f'; if(v>=50)return '#e0b83e'; return '#b44b4b'}
function barColor(v){v=Number(v)||0; if(v>=70)return '#34d848'; if(v>=50)return '#f3d421'; return '#e21d2f'}
function isaMiniBar(v){return `<div class="isaMiniBar"><span style="width:${Number(v)||0}%;background:${barColor(v)}"></span><em>${esc(v)}%</em></div>`}
function isaComparisonTable(categories){return `<section class="reportSection isaReportBlock"><h3>Comparison Chart</h3><div class="isaComparisonGrid"><div class="isaGridHeader">Profiles</div>${categories.map(c=>`<div class="isaGridHeader">${esc(c.name)}</div>`).join('')}<div class="isaRowLabel">Planter</div>${categories.map(c=>`<div class="isaGridCell">${isaMiniBar(c.score)}</div>`).join('')}<div class="isaRowLabel">Benchmark</div>${categories.map(c=>`<div class="isaGridCell">${isaMiniBar(c.benchmark)}</div>`).join('')}<div class="isaRowLabel">Median</div>${categories.map(c=>`<div class="isaGridCell">${isaMiniBar(c.median)}</div>`).join('')}</div></section>`}
function isaTopStrip(categories){return `<div class="isaScoreStrip">${categories.map(c=>`<div class="isaStripItem"><strong>${esc(c.name)}</strong><span style="background:${barColor(c.score)}"></span><em>${esc(c.score)}%</em></div>`).join('')}</div>`}
function isaInDepth(answers){const rows=Object.keys(answers||{}).map(k=>({id:Number(k),...(answers[k]||{})})).filter(x=>x.id).sort((a,b)=>a.id-b.id); return `<section class="reportSection isaReportBlock"><h3>ISA in Depth</h3><table class="isaDepthTable"><thead><tr><th>No.</th><th>Question</th><th>Answer</th><th>Group</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.question)}</td><td>${esc(r.answer)}</td><td>${esc(r.group)}</td></tr>`).join('')}</tbody></table></section>`}
function isaReportHtml(record){const c=record.candidate||{}; const s=record.scores||{}; const cats=s.categories||[]; const pct=s.overall||record.overall||0; return `<div class="isaReport"><div class="isaReportTitle"><div><h2>${esc(c.name||'Candidate')} ISA-Style Score</h2><p class="muted">${esc(c.email||'')} · ${esc(c.phone||'')} · ${esc(c.state||'')} / ${esc(c.region||record.region||'')} Region</p></div><div class="isaOverall" style="border-color:${scoreColor(pct)}"><strong>${esc(pct)}%</strong><span>${esc(s.overallLabel||record.overallLabel||'')}</span></div></div>${isaTopStrip(cats)}${isaComparisonTable(cats)}<section class="reportSection isaReportBlock"><h3>Readiness Snapshot</h3><p class="muted">This report summarizes practical ministry readiness across four areas: church planting exposure, entrepreneurial leadership, ministry experience, and relational evangelism. Scores are shown against benchmark and median reference points so reviewers can quickly see where the candidate is above, near, or below the model.</p></section><section class="reportSection isaReportBlock"><h3>Category Interpretation</h3><div class="isaCategoryCards">${cats.map(cat=>`<article class="isaCategoryCard"><div class="isaCategoryAccent" style="background:${barColor(cat.score)}"></div><div><h4>${esc(cat.name)} <span>${esc(cat.score)}% · ${esc(cat.label)}</span></h4><p>${esc(cat.description||'')}</p><small>Benchmark ${esc(cat.benchmark)}% · Median ${esc(cat.median)}%</small></div></article>`).join('')}</div></section>${isaInDepth(record.answers||{})}</div>`}
(async function(){dcAuth.setupLogout(); const user=await dcAuth.requireUser(); if(!user)return; const id=new URLSearchParams(location.search).get('id'); const section=document.getElementById('report'); if(!id){section.innerHTML='<div class="card">No report selected.</div>';return} const sb=await dcAuth.getSupabaseClient(); const {data,error}=await sb.from('assessment_results').select('*').eq('id',id).eq('user_id',user.id).maybeSingle(); if(error||!data){section.innerHTML=`<div class="card">${esc(error?.message||'Report not found.')}</div>`;return} const c=data.candidate||{}; const s=data.scores||{}; if(s.assessmentType==='isa_readiness'){section.innerHTML=isaReportHtml(data)+'<div class="actions"><button onclick="downloadStoredReport()">Download Report</button></div>'; window.currentReport={candidate:c,scores:s,answers:data.answers||{}}; return} section.innerHTML=`<div class="reportHeader"><h2>Discernment Center Candidate Assessment Report</h2><p>${esc(c.name||'')} · ${esc(c.state||'')} · ${esc(c.region||data.region||'')} Region</p><div class="overallCard"><span>Overall Readiness</span><strong>${esc(s.overall||data.overall)}</strong><em>${esc(s.overallLabel||data.overall_label)}</em></div></div>${visualScoreChart(s.results||[])}<div class="actions"><button onclick="downloadStoredReport()">Download Report</button></div>`; window.currentReport={candidate:c,scores:s,answers:data.answers||{}}})();
async function downloadStoredReport(){const fn=window.currentReport?.scores?.assessmentType==='isa_readiness'?'report-isa-pdf':'report-pdf'; const res=await fetch(`/.netlify/functions/${fn}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(window.currentReport)}); const blob=await res.blob(); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=window.currentReport?.scores?.assessmentType==='isa_readiness'?'ministry-readiness-report.pdf':'discernment-report.pdf'; a.click(); URL.revokeObjectURL(a.href)}
